/*
 * Copyright (C) 2014 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.gct.testing.dimension;

import com.google.common.collect.ImmutableList;

import java.util.List;

import static com.google.gct.testing.dimension.LanguageDimension.Language;

public class AllLanguages {
    static final List<Language> LANGUAGES = ImmutableList.of();
    //new Language("af", "Afrikaans"),
    //new Language("af_NA", "Afrikaans (Namibia)"),
    //new Language("af_ZA", "Afrikaans (South Africa)"),
    //new Language("agq", "Aghem"),
    //new Language("agq_CM", "Aghem (Cameroon)"),
    //new Language("ak", "Akan"),
    //new Language("ak_GH", "Akan (Ghana)"),
    //new Language("am", "Amharic"),
    //new Language("am_ET", "Amharic (Ethiopia)"),
    //new Language("ar", "Arabic"),
    //new Language("ar_001", "Arabic (World)"),
    //new Language("ar_AE", "Arabic (United Arab Emirates)"),
    //new Language("ar_BH", "Arabic (Bahrain)"),
    //new Language("ar_DZ", "Arabic (Algeria)"),
    //new Language("ar_EG", "Arabic (Egypt)"),
    //new Language("ar_IQ", "Arabic (Iraq)"),
    //new Language("ar_JO", "Arabic (Jordan)"),
    //new Language("ar_KW", "Arabic (Kuwait)"),
    //new Language("ar_LB", "Arabic (Lebanon)"),
    //new Language("ar_LY", "Arabic (Libya)"),
    //new Language("ar_MA", "Arabic (Morocco)"),
    //new Language("ar_OM", "Arabic (Oman)"),
    //new Language("ar_QA", "Arabic (Qatar)"),
    //new Language("ar_SA", "Arabic (Saudi Arabia)"),
    //new Language("ar_SD", "Arabic (Sudan)"),
    //new Language("ar_SY", "Arabic (Syria)"),
    //new Language("ar_TN", "Arabic (Tunisia)"),
    //new Language("ar_YE", "Arabic (Yemen)"),
    //new Language("as", "Assamese"),
    //new Language("as_IN", "Assamese (India)"),
    //new Language("asa", "Asu"),
    //new Language("asa_TZ", "Asu (Tanzania)"),
    //new Language("az", "Azerbaijani"),
    //new Language("az_Cyrl", "Azerbaijani (Cyrillic)"),
    //new Language("az_Cyrl_AZ", "Azerbaijani (Cyrillic, Azerbaijan)"),
    //new Language("az_Latn", "Azerbaijani (Latin)"),
    //new Language("az_Latn_AZ", "Azerbaijani (Latin, Azerbaijan)"),
    //new Language("bas", "Basaa"),
    //new Language("bas_CM", "Basaa (Cameroon)"),
    //new Language("be", "Belarusian"),
    //new Language("be_BY", "Belarusian (Belarus)"),
    //new Language("bem", "Bemba"),
    //new Language("bem_ZM", "Bemba (Zambia)"),
    //new Language("bez", "Bena"),
    //new Language("bez_TZ", "Bena (Tanzania)"),
    //new Language("bg", "Bulgarian"),
    //new Language("bg_BG", "Bulgarian (Bulgaria)"),
    //new Language("bm", "Bambara"),
    //new Language("bm_ML", "Bambara (Mali)"),
    //new Language("bn", "Bengali"),
    //new Language("bn_BD", "Bengali (Bangladesh)"),
    //new Language("bn_IN", "Bengali (India)"),
    //new Language("bo", "Tibetan"),
    //new Language("bo_CN", "Tibetan (China)"),
    //new Language("bo_IN", "Tibetan (India)"),
    //new Language("br", "Breton"),
    //new Language("br_FR", "Breton (France)"),
    //new Language("brx", "Bodo"),
    //new Language("brx_IN", "Bodo (India)"),
    //new Language("bs", "Bosnian"),
    //new Language("bs_BA", "Bosnian (Bosnia and Herzegovina)"),
    //new Language("ca", "Catalan"),
    //new Language("ca_ES", "Catalan (Spain)"),
    //new Language("cgg", "Chiga"),
    //new Language("cgg_UG", "Chiga (Uganda)"),
    //new Language("chr", "Cherokee"),
    //new Language("chr_US", "Cherokee (United States)"),
    //new Language("cs", "Czech"),
    //new Language("cs_CZ", "Czech (Czech Republic)"),
    //new Language("cy", "Welsh"),
    //new Language("cy_GB", "Welsh (United Kingdom)"),
    //new Language("da", "Danish"),
    //new Language("da_DK", "Danish (Denmark)"),
    //new Language("dav", "Taita"),
    //new Language("dav_KE", "Taita (Kenya)"),
    //new Language("de", "German"),
    //new Language("de_AT", "German (Austria)"),
    //new Language("de_BE", "German (Belgium)"),
    //new Language("de_CH", "German (Switzerland)"),
    //new Language("de_DE", "German (Germany)"),
    //new Language("de_LI", "German (Liechtenstein)"),
    //new Language("de_LU", "German (Luxembourg)"),
    //new Language("dje", "Zarma"),
    //new Language("dje_NE", "Zarma (Niger)"),
    //new Language("dua", "Duala"),
    //new Language("dua_CM", "Duala (Cameroon)"),
    //new Language("dyo", "Jola-Fonyi"),
    //new Language("dyo_SN", "Jola-Fonyi (Senegal)"),
    //new Language("ebu", "Embu"),
    //new Language("ebu_KE", "Embu (Kenya)"),
    //new Language("ee", "Ewe"),
    //new Language("ee_GH", "Ewe (Ghana)"),
    //new Language("ee_TG", "Ewe (Togo)"),
    //new Language("el", "Greek"),
    //new Language("el_CY", "Greek (Cyprus)"),
    //new Language("el_GR", "Greek (Greece)"),
    //new Language("en", "English"),
    //new Language("en_AS", "English (American Samoa)"),
    //new Language("en_AU", "English (Australia)"),
    //new Language("en_BB", "English (Barbados)"),
    //new Language("en_BE", "English (Belgium)"),
    //new Language("en_BM", "English (Bermuda)"),
    //new Language("en_BW", "English (Botswana)"),
    //new Language("en_BZ", "English (Belize)"),
    //new Language("en_CA", "English (Canada)"),
    //new Language("en_GB", "English (United Kingdom)"),
    //new Language("en_GU", "English (Guam)"),
    //new Language("en_GY", "English (Guyana)"),
    //new Language("en_HK", "English (Hong Kong SAR China)"),
    //new Language("en_IE", "English (Ireland)"),
    //new Language("en_IN", "English (India)"),
    //new Language("en_JM", "English (Jamaica)"),
    //new Language("en_MH", "English (Marshall Islands)"),
    //new Language("en_MP", "English (Northern Mariana Islands)"),
    //new Language("en_MT", "English (Malta)"),
    //new Language("en_MU", "English (Mauritius)"),
    //new Language("en_NA", "English (Namibia)"),
    //new Language("en_NZ", "English (New Zealand)"),
    //new Language("en_PH", "English (Philippines)"),
    //new Language("en_PK", "English (Pakistan)"),
    //new Language("en_SG", "English (Singapore)"),
    //new Language("en_TT", "English (Trinidad and Tobago)"),
    //new Language("en_UM", "English (U.S. Minor Outlying Islands)"),
    //new Language("en_US", "English (United States)"),
    //new Language("en_US_POSIX", "English (United States, Computer)"),
    //new Language("en_VI", "English (U.S. Virgin Islands)"),
    //new Language("en_ZA", "English (South Africa)"),
    //new Language("en_ZW", "English (Zimbabwe)"),
    //new Language("eo", "Esperanto"),
    //new Language("es", "Spanish"),
    //new Language("es_419", "Spanish (Latin America)"),
    //new Language("es_AR", "Spanish (Argentina)"),
    //new Language("es_BO", "Spanish (Bolivia)"),
    //new Language("es_CL", "Spanish (Chile)"),
    //new Language("es_CO", "Spanish (Colombia)"),
    //new Language("es_CR", "Spanish (Costa Rica)"),
    //new Language("es_DO", "Spanish (Dominican Republic)"),
    //new Language("es_EC", "Spanish (Ecuador)"),
    //new Language("es_ES", "Spanish (Spain)"),
    //new Language("es_GQ", "Spanish (Equatorial Guinea)"),
    //new Language("es_GT", "Spanish (Guatemala)"),
    //new Language("es_HN", "Spanish (Honduras)"),
    //new Language("es_MX", "Spanish (Mexico)"),
    //new Language("es_NI", "Spanish (Nicaragua)"),
    //new Language("es_PA", "Spanish (Panama)"),
    //new Language("es_PE", "Spanish (Peru)"),
    //new Language("es_PR", "Spanish (Puerto Rico)"),
    //new Language("es_PY", "Spanish (Paraguay)"),
    //new Language("es_SV", "Spanish (El Salvador)"),
    //new Language("es_US", "Spanish (United States)"),
    //new Language("es_UY", "Spanish (Uruguay)"),
    //new Language("es_VE", "Spanish (Venezuela)"),
    //new Language("et", "Estonian"),
    //new Language("et_EE", "Estonian (Estonia)"),
    //new Language("eu", "Basque"),
    //new Language("eu_ES", "Basque (Spain)"),
    //new Language("ewo", "Ewondo"),
    //new Language("ewo_CM", "Ewondo (Cameroon)"),
    //new Language("fa", "Persian"),
    //new Language("fa_AF", "Persian (Afghanistan)"),
    //new Language("fa_IR", "Persian (Iran)"),
    //new Language("ff", "Fulah"),
    //new Language("ff_SN", "Fulah (Senegal)"),
    //new Language("fi", "Finnish"),
    //new Language("fi_FI", "Finnish (Finland)"),
    //new Language("fil", "Filipino"),
    //new Language("fil_PH", "Filipino (Philippines)"),
    //new Language("fo", "Faroese"),
    //new Language("fo_FO", "Faroese (Faroe Islands)"),
    //new Language("fr", "French"),
    //new Language("fr_BE", "French (Belgium)"),
    //new Language("fr_BF", "French (Burkina Faso)"),
    //new Language("fr_BI", "French (Burundi)"),
    //new Language("fr_BJ", "French (Benin)"),
    //new Language("fr_BL", "French (Saint Barthélemy)"),
    //new Language("fr_CA", "French (Canada)"),
    //new Language("fr_CD", "French (Congo - Kinshasa)"),
    //new Language("fr_CF", "French (Central African Republic)"),
    //new Language("fr_CG", "French (Congo - Brazzaville)"),
    //new Language("fr_CH", "French (Switzerland)"),
    //new Language("fr_CI", "French (Côte d’Ivoire)"),
    //new Language("fr_CM", "French (Cameroon)"),
    //new Language("fr_DJ", "French (Djibouti)"),
    //new Language("fr_FR", "French (France)"),
    //new Language("fr_GA", "French (Gabon)"),
    //new Language("fr_GF", "French (French Guiana)"),
    //new Language("fr_GN", "French (Guinea)"),
    //new Language("fr_GP", "French (Guadeloupe)"),
    //new Language("fr_GQ", "French (Equatorial Guinea)"),
    //new Language("fr_KM", "French (Comoros)"),
    //new Language("fr_LU", "French (Luxembourg)"),
    //new Language("fr_MC", "French (Monaco)"),
    //new Language("fr_MF", "French (Saint Martin)"),
    //new Language("fr_MG", "French (Madagascar)"),
    //new Language("fr_ML", "French (Mali)"),
    //new Language("fr_MQ", "French (Martinique)"),
    //new Language("fr_NE", "French (Niger)"),
    //new Language("fr_RE", "French (Réunion)"),
    //new Language("fr_RW", "French (Rwanda)"),
    //new Language("fr_SN", "French (Senegal)"),
    //new Language("fr_TD", "French (Chad)"),
    //new Language("fr_TG", "French (Togo)"),
    //new Language("fr_YT", "French (Mayotte)"),
    //new Language("ga", "Irish"),
    //new Language("ga_IE", "Irish (Ireland)"),
    //new Language("gl", "Galician"),
    //new Language("gl_ES", "Galician (Spain)"),
    //new Language("gsw", "Swiss German"),
    //new Language("gsw_CH", "Swiss German (Switzerland)"),
    //new Language("gu", "Gujarati"),
    //new Language("gu_IN", "Gujarati (India)"),
    //new Language("guz", "Gusii"),
    //new Language("guz_KE", "Gusii (Kenya)"),
    //new Language("gv", "Manx"),
    //new Language("gv_GB", "Manx (United Kingdom)"),
    //new Language("ha", "Hausa"),
    //new Language("ha_Latn", "Hausa (Latin)"),
    //new Language("ha_Latn_GH", "Hausa (Latin, Ghana)"),
    //new Language("ha_Latn_NE", "Hausa (Latin, Niger)"),
    //new Language("ha_Latn_NG", "Hausa (Latin, Nigeria)"),
    //new Language("haw", "Hawaiian"),
    //new Language("haw_US", "Hawaiian (United States)"),
    //new Language("he", "Hebrew"),
    //new Language("he_IL", "Hebrew (Israel)"),
    //new Language("hi", "Hindi"),
    //new Language("hi_IN", "Hindi (India)"),
    //new Language("hr", "Croatian"),
    //new Language("hr_HR", "Croatian (Croatia)"),
    //new Language("hu", "Hungarian"),
    //new Language("hu_HU", "Hungarian (Hungary)"),
    //new Language("hy", "Armenian"),
    //new Language("hy_AM", "Armenian (Armenia)"),
    //new Language("id", "Indonesian"),
    //new Language("id_ID", "Indonesian (Indonesia)"),
    //new Language("ig", "Igbo"),
    //new Language("ig_NG", "Igbo (Nigeria)"),
    //new Language("ii", "Sichuan Yi"),
    //new Language("ii_CN", "Sichuan Yi (China)"),
    //new Language("is", "Icelandic"),
    //new Language("is_IS", "Icelandic (Iceland)"),
    //new Language("it", "Italian"),
    //new Language("it_CH", "Italian (Switzerland)"),
    //new Language("it_IT", "Italian (Italy)"),
    //new Language("ja", "Japanese"),
    //new Language("ja_JP", "Japanese (Japan)"),
    //new Language("jmc", "Machame"),
    //new Language("jmc_TZ", "Machame (Tanzania)"),
    //new Language("ka", "Georgian"),
    //new Language("ka_GE", "Georgian (Georgia)"),
    //new Language("kab", "Kabyle"),
    //new Language("kab_DZ", "Kabyle (Algeria)"),
    //new Language("kam", "Kamba"),
    //new Language("kam_KE", "Kamba (Kenya)"),
    //new Language("kde", "Makonde"),
    //new Language("kde_TZ", "Makonde (Tanzania)"),
    //new Language("kea", "Kabuverdianu"),
    //new Language("kea_CV", "Kabuverdianu (Cape Verde)"),
    //new Language("khq", "Koyra Chiini"),
    //new Language("khq_ML", "Koyra Chiini (Mali)"),
    //new Language("ki", "Kikuyu"),
    //new Language("ki_KE", "Kikuyu (Kenya)"),
    //new Language("kk", "Kazakh"),
    //new Language("kk_Cyrl", "Kazakh (Cyrillic)"),
    //new Language("kk_Cyrl_KZ", "Kazakh (Cyrillic, Kazakhstan)"),
    //new Language("kl", "Kalaallisut"),
    //new Language("kl_GL", "Kalaallisut (Greenland)"),
    //new Language("kln", "Kalenjin"),
    //new Language("kln_KE", "Kalenjin (Kenya)"),
    //new Language("km", "Khmer"),
    //new Language("km_KH", "Khmer (Cambodia)"),
    //new Language("kn", "Kannada"),
    //new Language("kn_IN", "Kannada (India)"),
    //new Language("ko", "Korean"),
    //new Language("ko_KR", "Korean (South Korea)"),
    //new Language("kok", "Konkani"),
    //new Language("kok_IN", "Konkani (India)"),
    //new Language("ksb", "Shambala"),
    //new Language("ksb_TZ", "Shambala (Tanzania)"),
    //new Language("ksf", "Bafia"),
    //new Language("ksf_CM", "Bafia (Cameroon)"),
    //new Language("kw", "Cornish"),
    //new Language("kw_GB", "Cornish (United Kingdom)"),
    //new Language("lag", "Langi"),
    //new Language("lag_TZ", "Langi (Tanzania)"),
    //new Language("lg", "Ganda"),
    //new Language("lg_UG", "Ganda (Uganda)"),
    //new Language("ln", "Lingala"),
    //new Language("ln_CD", "Lingala (Congo - Kinshasa)"),
    //new Language("ln_CG", "Lingala (Congo - Brazzaville)"),
    //new Language("lt", "Lithuanian"),
    //new Language("lt_LT", "Lithuanian (Lithuania)"),
    //new Language("lu", "Luba-Katanga"),
    //new Language("lu_CD", "Luba-Katanga (Congo - Kinshasa)"),
    //new Language("luo", "Luo"),
    //new Language("luo_KE", "Luo (Kenya)"),
    //new Language("luy", "Luyia"),
    //new Language("luy_KE", "Luyia (Kenya)"),
    //new Language("lv", "Latvian"),
    //new Language("lv_LV", "Latvian (Latvia)"),
    //new Language("mas", "Masai"),
    //new Language("mas_KE", "Masai (Kenya)"),
    //new Language("mas_TZ", "Masai (Tanzania)"),
    //new Language("mer", "Meru"),
    //new Language("mer_KE", "Meru (Kenya)"),
    //new Language("mfe", "Morisyen"),
    //new Language("mfe_MU", "Morisyen (Mauritius)"),
    //new Language("mg", "Malagasy"),
    //new Language("mg_MG", "Malagasy (Madagascar)"),
    //new Language("mgh", "Makhuwa-Meetto"),
    //new Language("mgh_MZ", "Makhuwa-Meetto (Mozambique)"),
    //new Language("mk", "Macedonian"),
    //new Language("mk_MK", "Macedonian (Macedonia)"),
    //new Language("ml", "Malayalam"),
    //new Language("ml_IN", "Malayalam (India)"),
    //new Language("mr", "Marathi"),
    //new Language("mr_IN", "Marathi (India)"),
    //new Language("ms", "Malay"),
    //new Language("ms_BN", "Malay (Brunei)"),
    //new Language("ms_MY", "Malay (Malaysia)"),
    //new Language("mt", "Maltese"),
    //new Language("mt_MT", "Maltese (Malta)"),
    //new Language("mua", "Mundang"),
    //new Language("mua_CM", "Mundang (Cameroon)"),
    //new Language("my", "Burmese"),
    //new Language("my_MM", "Burmese (Myanmar [Burma])"),
    //new Language("naq", "Nama"),
    //new Language("naq_NA", "Nama (Namibia)"),
    //new Language("nb", "Norwegian Bokmål"),
    //new Language("nb_NO", "Norwegian Bokmål (Norway)"),
    //new Language("nd", "North Ndebele"),
    //new Language("nd_ZW", "North Ndebele (Zimbabwe)"),
    //new Language("ne", "Nepali"),
    //new Language("ne_IN", "Nepali (India)"),
    //new Language("ne_NP", "Nepali (Nepal)"),
    //new Language("nl", "Dutch"),
    //new Language("nl_AW", "Dutch (Aruba)"),
    //new Language("nl_BE", "Dutch (Belgium)"),
    //new Language("nl_CW", "Dutch (Curaçao)"),
    //new Language("nl_NL", "Dutch (Netherlands)"),
    //new Language("nl_SX", "Dutch (Sint Maarten)"),
    //new Language("nmg", "Kwasio"),
    //new Language("nmg_CM", "Kwasio (Cameroon)"),
    //new Language("nn", "Norwegian Nynorsk"),
    //new Language("nn_NO", "Norwegian Nynorsk (Norway)"),
    //new Language("nus", "Nuer"),
    //new Language("nus_SD", "Nuer (Sudan)"),
    //new Language("nyn", "Nyankole"),
    //new Language("nyn_UG", "Nyankole (Uganda)"),
    //new Language("om", "Oromo"),
    //new Language("om_ET", "Oromo (Ethiopia)"),
    //new Language("om_KE", "Oromo (Kenya)"),
    //new Language("or", "Oriya"),
    //new Language("or_IN", "Oriya (India)"),
    //new Language("pa", "Punjabi"),
    //new Language("pa_Arab", "Punjabi (Arabic)"),
    //new Language("pa_Arab_PK", "Punjabi (Arabic, Pakistan)"),
    //new Language("pa_Guru", "Punjabi (Gurmukhi)"),
    //new Language("pa_Guru_IN", "Punjabi (Gurmukhi, India)"),
    //new Language("pl", "Polish"),
    //new Language("pl_PL", "Polish (Poland)"),
    //new Language("ps", "Pashto"),
    //new Language("ps_AF", "Pashto (Afghanistan)"),
    //new Language("pt", "Portuguese"),
    //new Language("pt_AO", "Portuguese (Angola)"),
    //new Language("pt_BR", "Portuguese (Brazil)"),
    //new Language("pt_GW", "Portuguese (Guinea-Bissau)"),
    //new Language("pt_MZ", "Portuguese (Mozambique)"),
    //new Language("pt_PT", "Portuguese (Portugal)"),
    //new Language("pt_ST", "Portuguese (São Tomé and Príncipe)"),
    //new Language("rm", "Romansh"),
    //new Language("rm_CH", "Romansh (Switzerland)"),
    //new Language("rn", "Rundi"),
    //new Language("rn_BI", "Rundi (Burundi)"),
    //new Language("ro", "Romanian"),
    //new Language("ro_MD", "Romanian (Moldova)"),
    //new Language("ro_RO", "Romanian (Romania)"),
    //new Language("rof", "Rombo"),
    //new Language("rof_TZ", "Rombo (Tanzania)"),
    //new Language("ru", "Russian"),
    //new Language("ru_MD", "Russian (Moldova)"),
    //new Language("ru_RU", "Russian (Russia)"),
    //new Language("ru_UA", "Russian (Ukraine)"),
    //new Language("rw", "Kinyarwanda"),
    //new Language("rw_RW", "Kinyarwanda (Rwanda)"),
    //new Language("rwk", "Rwa"),
    //new Language("rwk_TZ", "Rwa (Tanzania)"),
    //new Language("saq", "Samburu"),
    //new Language("saq_KE", "Samburu (Kenya)"),
    //new Language("sbp", "Sangu"),
    //new Language("sbp_TZ", "Sangu (Tanzania)"),
    //new Language("seh", "Sena"),
    //new Language("seh_MZ", "Sena (Mozambique)"),
    //new Language("ses", "Koyraboro Senni"),
    //new Language("ses_ML", "Koyraboro Senni (Mali)"),
    //new Language("sg", "Sango"),
    //new Language("sg_CF", "Sango (Central African Republic)"),
    //new Language("shi", "Tachelhit"),
    //new Language("shi_Latn", "Tachelhit (Latin)"),
    //new Language("shi_Latn_MA", "Tachelhit (Latin, Morocco)"),
    //new Language("shi_Tfng", "Tachelhit (Tifinagh)"),
    //new Language("shi_Tfng_MA", "Tachelhit (Tifinagh, Morocco)"),
    //new Language("si", "Sinhala"),
    //new Language("si_LK", "Sinhala (Sri Lanka)"),
    //new Language("sk", "Slovak"),
    //new Language("sk_SK", "Slovak (Slovakia)"),
    //new Language("sl", "Slovenian"),
    //new Language("sl_SI", "Slovenian (Slovenia)"),
    //new Language("sn", "Shona"),
    //new Language("sn_ZW", "Shona (Zimbabwe)"),
    //new Language("so", "Somali"),
    //new Language("so_DJ", "Somali (Djibouti)"),
    //new Language("so_ET", "Somali (Ethiopia)"),
    //new Language("so_KE", "Somali (Kenya)"),
    //new Language("so_SO", "Somali (Somalia)"),
    //new Language("sq", "Albanian"),
    //new Language("sq_AL", "Albanian (Albania)"),
    //new Language("sr", "Serbian"),
    //new Language("sr_Cyrl", "Serbian (Cyrillic)"),
    //new Language("sr_Cyrl_BA", "Serbian (Cyrillic, Bosnia and Herzegovina)"),
    //new Language("sr_Cyrl_ME", "Serbian (Cyrillic, Montenegro)"),
    //new Language("sr_Cyrl_RS", "Serbian (Cyrillic, Serbia)"),
    //new Language("sr_Latn", "Serbian (Latin)"),
    //new Language("sr_Latn_BA", "Serbian (Latin, Bosnia and Herzegovina)"),
    //new Language("sr_Latn_ME", "Serbian (Latin, Montenegro)"),
    //new Language("sr_Latn_RS", "Serbian (Latin, Serbia)"),
    //new Language("sv", "Swedish"),
    //new Language("sv_FI", "Swedish (Finland)"),
    //new Language("sv_SE", "Swedish (Sweden)"),
    //new Language("sw", "Swahili"),
    //new Language("sw_KE", "Swahili (Kenya)"),
    //new Language("sw_TZ", "Swahili (Tanzania)"),
    //new Language("swc", "Congo Swahili"),
    //new Language("swc_CD", "Congo Swahili (Congo - Kinshasa)"),
    //new Language("ta", "Tamil"),
    //new Language("ta_IN", "Tamil (India)"),
    //new Language("ta_LK", "Tamil (Sri Lanka)"),
    //new Language("te", "Telugu"),
    //new Language("te_IN", "Telugu (India)"),
    //new Language("teo", "Teso"),
    //new Language("teo_KE", "Teso (Kenya)"),
    //new Language("teo_UG", "Teso (Uganda)"),
    //new Language("th", "Thai"),
    //new Language("th_TH", "Thai (Thailand)"),
    //new Language("ti", "Tigrinya"),
    //new Language("ti_ER", "Tigrinya (Eritrea)"),
    //new Language("ti_ET", "Tigrinya (Ethiopia)"),
    //new Language("to", "Tongan"),
    //new Language("to_TO", "Tongan (Tonga)"),
    //new Language("tr", "Turkish"),
    //new Language("tr_TR", "Turkish (Turkey)"),
    //new Language("twq", "Tasawaq"),
    //new Language("twq_NE", "Tasawaq (Niger)"),
    //new Language("tzm", "Central Morocco Tamazight"),
    //new Language("tzm_Latn", "Central Morocco Tamazight (Latin)"),
    //new Language("tzm_Latn_MA", "Central Morocco Tamazight (Latin, Morocco)"),
    //new Language("uk", "Ukrainian"),
    //new Language("uk_UA", "Ukrainian (Ukraine)"),
    //new Language("ur", "Urdu"),
    //new Language("ur_IN", "Urdu (India)"),
    //new Language("ur_PK", "Urdu (Pakistan)"),
    //new Language("uz", "Uzbek"),
    //new Language("uz_Arab", "Uzbek (Arabic)"),
    //new Language("uz_Arab_AF", "Uzbek (Arabic, Afghanistan)"),
    //new Language("uz_Cyrl", "Uzbek (Cyrillic)"),
    //new Language("uz_Cyrl_UZ", "Uzbek (Cyrillic, Uzbekistan)"),
    //new Language("uz_Latn", "Uzbek (Latin)"),
    //new Language("uz_Latn_UZ", "Uzbek (Latin, Uzbekistan)"),
    //new Language("vai", "Vai"),
    //new Language("vai_Latn", "Vai (Latin)"),
    //new Language("vai_Latn_LR", "Vai (Latin, Liberia)"),
    //new Language("vai_Vaii", "Vai (Vai)"),
    //new Language("vai_Vaii_LR", "Vai (Vai, Liberia)"),
    //new Language("vi", "Vietnamese"),
    //new Language("vi_VN", "Vietnamese (Vietnam)"),
    //new Language("vun", "Vunjo"),
    //new Language("vun_TZ", "Vunjo (Tanzania)"),
    //new Language("xog", "Soga"),
    //new Language("xog_UG", "Soga (Uganda)"),
    //new Language("yav", "Yangben"),
    //new Language("yav_CM", "Yangben (Cameroon)"),
    //new Language("yo", "Yoruba"),
    //new Language("yo_NG", "Yoruba (Nigeria)"),
    //new Language("zh", "Chinese"),
    //new Language("zh_Hans", "Chinese (Simplified)"),
    //new Language("zh_Hans_CN", "Chinese (Simplified, China)"),
    //new Language("zh_Hans_HK", "Chinese (Simplified, Hong Kong SAR China)"),
    //new Language("zh_Hans_MO", "Chinese (Simplified, Macau SAR China)"),
    //new Language("zh_Hans_SG", "Chinese (Simplified, Singapore)"),
    //new Language("zh_Hant", "Chinese (Traditional)"),
    //new Language("zh_Hant_HK", "Chinese (Traditional, Hong Kong SAR China)"),
    //new Language("zh_Hant_MO", "Chinese (Traditional, Macau SAR China)"),
    //new Language("zh_Hant_TW", "Chinese (Traditional, Taiwan)"),
    //new Language("zu", "Zulu"),
    //new Language("zu_ZA", "Zulu (South Africa)"));
}
